title: Hsing-Yi Chu # your name (or website title) here
logo: "/images/avatar_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am Hsing-Yi (Sean) Chu, a recent graduate with a Bachelor's degree in Economics from the University of Queensland. 
  My academic journey has equipped me with a comprehensive understanding of economic principles, complemented by a specialization in data analysis, 
  visualization, and interpretation within the realms of Economics and Finance. 
  <br><br>
  Bachelor of Economics with a major in Quantitative Analysis, University of Queensland 2023
  <br><br>
  <a href="https://www.linkedin.com/in/hsing-yi-sean-chu">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
